### ISSUE TITLE
ndarray support

### ISSUE THREAD

**Issue by atomicmac** [124C41p/betterproto-rust-codec#1]
It would be great if this could also serialize numpy ndarrays.
There are a few other projects that support ndarrays over gRPC, but none for betterproto.

@Gobot1234 suggested this project when I mentioned ndarrays in the betterproto issues https://github.com/danielgtaylor/python-betterproto/pull/560#issuecomment-2016610988

**Comment by 124C41p** [comment]
Hi, I don't think it is possible (right now) what you are asking for: This package provides alternative (de-)serializers for betterproto messages which are faster than the original ones, but have the same semantics. Deserializing into numpy arrays instead of Python lists would violate the type hints generated by the betterproto compiler. So we cannot make changes here without relaxing the auto generated types first.

If you care about performance, I would still recommend to use this package by installing betterproto with the `rust-codec` feature enabled, and convert between Python lists and numpy arrays yourself (which is actually quite fast).

As there is currently no betterproto version released which uses this package, you need to install it from github though:

```bash
pip install "betterproto[rust-codec] @ git+https://github.com/danielgtaylor/python-betterproto.git"
```

**Comment by 124C41p** [comment]
Serializing numpy arrays should work out of the box when using this package. There is currently one exception: serializing numpy boolean arrays will not work as of version 0.1.0 due to an issue with one of my dependencies. However, this issue is fixed in the latest version which was actually released three days ago. So I will update this package accordingly soon.

Note that there is currently no betterproto version released which uses this package, so you need to install it from github:
```bash
pip install "betterproto[rust-codec] @ git+https://github.com/danielgtaylor/python-betterproto.git"
```
